author: someone
author_link: ""
license: ""
license_link: ""
app_version: 1.0

short_description: A generic app

description: |
  This is an app for MicroHydra.

installation_instructions: |
  Copy the app into your `/apps` folder.


devices:
- Cardputer
